schema_version = 1

[[instances]]
id = "backrooms-vol2"
name = "THE BACKROOMS vol. 2"
accent_color = "#e8a04a"
description = "Explora los Backrooms. Vol. 2"
logo = "https://eufonia.studio/cdn-cgi/image/width=3840,quality=75,format=auto/_next/static/media/01_backrooms2.e544faf8.png"
background = "https://eufonia.studio/cdn-cgi/image/width=3840,quality=75,format=auto/_next/static/media/01_backrooms2.e544faf8.png"
accent_color = "#e11d8a"
# Enlace directo de Dropbox (el launcher convierte dl=0 → dl=1 automáticamente)
zip_url = "https://www.dropbox.com/scl/fi/qerqjqxabccl7d9i05tn8/config.zip?rlkey=3gxwt7ryef8nmfx1jnffvw2f7&st=fjm5ds65&dl=1"
mc_version = "1.19.4"
loader = "fabric"
loader_version = "0.16.14"

[[instances]]
id = "eubones2"
name = "Uebones Show 2"
accent_color = "#e8a04a"
description = "pvp epico"
logo = "https://raw.githubusercontent.com/lickn87-collab/img/refs/heads/main/WBNS_Show_pfp.webp"
background = "https://eufonia.studio/cdn-cgi/image/quality=75,format=auto,width=2560/images/minecraft/34_webones_show/mr_webon.png"
accent_color = "#e11d8a"
# Enlace directo de Dropbox (el launcher convierte dl=0 → dl=1 automáticamente)
zip_url = "https://www.dropbox.com/scl/fi/uje9rx0w9hrqo9n6giy1x/Sandbox-1.19.4.zip?rlkey=r6bhr5z0hi151o44zlumm945o&st=msarf0lf&dl=1"
mc_version = "1.19.4"
loader = "fabric"
loader_version = "0.16.14"
